### PR TITLE
creating message boxes using tkinter module of python

### PR DESCRIPTION
**Pull request by vaibhavkumar779**
message box is directory with multiple python program that create message boxes with tkinter
I have also attached a README file for help

### CODE REVIEW

**Comment by Veerhan-glitch** [comment]
Hi thanks for contributing to the repo!
This all is very good work but can you pls also integrate it in the already existing things?
Happy hactoberfest!

**Comment by vaibhavkumar779** [comment]
Can you explain with what things you mean to say, each file only generates different message box but in the end it is same

**Comment by Veerhan-glitch** [comment]
what i mean to say is that pls make the existing work use your templates like i dont think this repo needs some of thes templats like ask cancel.  u cold do something to make the inputs from tinkerit.

**Comment by vaibhavkumar779** [comment]
Ok

**Comment by Veerhan-glitch** [comment]
ok then i am closing this pull req you can do that in new one.
Happy coding!

**Pull request closed without merging**
